Add support of Linux ARM64
tfutils/tfenv pull request #280
Opened 2021-06-30 13:08 UTC by amulobaev

2021-07-16 10:43 UTC, gchenuet requested changes
Adding Apple Silicon arm64 support.

Thanks for your work !

2021-07-16 10:43 UTC, gchenuet commented on libexec/tfenv-install
> +  aarch64*)
Please add support for Apple Silicon CPU:

`  aarch64* | arm64*)`

2021-07-16 10:43 UTC, gchenuet commented on libexec/tfenv-install
> +# Add support of Linux ARM64
`# Add support of ARM64 for Linux & Apple Silicon`

2021-07-16 11:24 UTC, amulobaev commented
> Adding Apple Silicon arm64 support.
> 
> Thanks for your work!

Thank you

2021-08-14 18:28 UTC, Zordrak approved these changes

2021-08-14 18:37 UTC, merged

2021-12-13 19:08 UTC, danielcompton commented
@Zordrak would you be able to tag a new release to include this when you get a chance? ref: https://github.com/tfutils/tfenv/issues/306

2022-01-22 22:37 UTC, nathanhruby commented
Note also that golang/go#42700 affects the amd version and sometimes tf barfs as a result