Fix use of -chdir with an absolute path
tfutils/tfenv pull request #355
Opened 2022-07-27 18:35 UTC by OJFord

Fixes #354.

2022-10-01 16:23 UTC, Zordrak requested changes
Tests fail because `realpath` is not available in the default toolset on macos.

2023-03-18 00:45 UTC, OJFord commented
> Tests fail because `realpath` is not available in the default toolset on macos.

Hi @Zordrak, I believe I fixed that issue if you have time for another look. Cheers.

2024-02-10 16:50 UTC, OJFord commented
Anything else still needed here @Zordrak?

2024-08-21 08:05 UTC, WitoldSlawko commented
@Zordrak update when this PR will be merged ?

It hangs like this for 6 months now...

2024-08-21 20:27 UTC, kvendingoldo commented
@WitoldSlawko looks like that tfenv is not supported anymore. You can switch to https://github.com/tofuutils/tenv

2025-07-04 13:25 UTC, Zordrak approved these changes

2025-07-04 13:26 UTC, merged